version: '2.27'

services:

  appreciate_frontend:
    container_name: appreciate_frontend
    restart: always
    build:
      context: ./app
      dockerfile: Dockerfile-nginx
        #    volumes:
        #      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        #      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
        #      - ./app/code:/code
    volumes:
      - ./data/form-save.txt:/code/form-save.txt.download
    networks:
      - shared
    logging:
        driver: "json-file"
        options:
            max-file: "5"
            max-size: "20m"

  appreciate_php:
    container_name: appreciate_php
    restart: always
    build:
      context: ./app
      dockerfile: Dockerfile-php
    env_file:
      - ./app/.env
    volumes:
      - ./data/form-save.txt:/code/form-save.txt
    networks:
      - shared
    logging:
        driver: "json-file"
        options:
            max-file: "5"
            max-size: "20m"



networks:
  shared:
    external: false
