FROM php:8.0.2-fpm

RUN docker-php-ext-install opcache && docker-php-ext-configure opcache --enable-opcache

COPY php/php.ini /usr/local/etc/php/php.ini
COPY php/www.conf /usr/local/etc/php-fpm.d/www.conf

WORKDIR /code

COPY ./.env /code/.env
COPY --chown=www-data:www-data code /code

USER www-data
